test

diff --git a/.github/workflows/php-unit-tests.yml b/.github/workflows/php-unit-tests.yml
--- a/.github/workflows/php-unit-tests.yml
+++ b/.github/workflows/php-unit-tests.yml
@@ -48,15 +48,93 @@ jobs:
       - name: Configure environment
         run: |
           # composer setup
+          # (php --ri relay 2>&1 > /dev/null) || sudo rm /etc/php/*/cli/conf.d/20-relay.ini
+          # COMPOSER_HOME="$(composer config home)"
+          # ([ -d "$COMPOSER_HOME" ] || mkdir "$COMPOSER_HOME") && cp .github/composer-config.json "$COMPOSER_HOME/config.json"
+          # SYMFONY_VERSION=$(grep ' VERSION = ' src/Symfony/Component/HttpKernel/Kernel.php | cut -d "'" -f2 | cut -d '.' -f 1-2)
+          # php .github/build-packages.php HEAD^ $SYMFONY_VERSION src/Symfony/Bridge/PhpUnit
+          # echo SYMFONY_VERSION=$SYMFONY_VERSION >> $GITHUB_ENV
+          # echo COMPOSER_ROOT_VERSION=$SYMFONY_VERSION.x-dev >> $GITHUB_ENV
+          # echo SYMFONY_REQUIRE=">=${SYMFONY_VERSION}" >> $GITHUB_ENV
+          # echo COLUMNS=150 >> $GITHUB_ENV
+          git config --global user.email ""
+          git config --global user.name "Symfony"
+          git config --global init.defaultBranch main
+          git config --global advice.detachedHead false
+
           (php --ri relay 2>&1 > /dev/null) || sudo rm /etc/php/*/cli/conf.d/20-relay.ini
+
           COMPOSER_HOME="$(composer config home)"
           ([ -d "$COMPOSER_HOME" ] || mkdir "$COMPOSER_HOME") && cp .github/composer-config.json "$COMPOSER_HOME/config.json"
+
+          echo COLUMNS=120 >> $GITHUB_ENV
+          echo PHPUNIT="$(pwd)/phpunit --exclude-group tty,benchmark,intl-data,integration" >> $GITHUB_ENV
+          echo COMPOSER_UP='composer update --no-progress --ansi'$([[ "" != low-deps ]] && echo ' --ignore-platform-req=php+') >> $GITHUB_ENV
+
+          SYMFONY_VERSIONS=$(git ls-remote -q --heads | cut -f2 | grep -o '/[1-9][0-9]*\.[0-9].*' | sort -V)
           SYMFONY_VERSION=$(grep ' VERSION = ' src/Symfony/Component/HttpKernel/Kernel.php | cut -d "'" -f2 | cut -d '.' -f 1-2)
-          php .github/build-packages.php HEAD^ $SYMFONY_VERSION src/Symfony/Bridge/PhpUnit
+          SYMFONY_FEATURE_BRANCH=$(curl -s https://raw.githubusercontent.com/symfony/recipes/flex/main/index.json | jq -r '.versions."dev-name"')
+
+          # Install the phpunit-bridge from a PR if required
+          #
+          # To run a PR with a patched phpunit-bridge, first submit the patch for the
+          # phpunit-bridge as a separate PR against the next feature-branch then
+          # uncomment and update the following line with that PR number
+          #SYMFONY_PHPUNIT_BRIDGE_PR=32886
+
+          if [[ $SYMFONY_PHPUNIT_BRIDGE_PR ]]; then
+            git fetch --depth=2 origin refs/pull/$SYMFONY_PHPUNIT_BRIDGE_PR/head
+            git rm -rq src/Symfony/Bridge/PhpUnit
+            git checkout -q FETCH_HEAD -- src/Symfony/Bridge/PhpUnit
+            SYMFONY_PHPUNIT_BRIDGE_REF=$(curl -s https://api.github.com/repos/symfony/symfony/pulls/$SYMFONY_PHPUNIT_BRIDGE_PR | jq -r .base.ref)
+            sed -i 's/"symfony\/phpunit-bridge": ".*"/"symfony\/phpunit-bridge": "'$SYMFONY_PHPUNIT_BRIDGE_REF'.x@dev"/' composer.json
+            rm -rf .phpunit
+          fi
+
+          # Create local composer packages for each patched components and reference them in composer.json files when cross-testing components
+          if [[ ! "" = *-deps ]]; then
+              php .github/build-packages.php HEAD^ $SYMFONY_VERSION src/Symfony/Bridge/PhpUnit
+          else
+            echo SYMFONY_DEPRECATIONS_HELPER=weak >> $GITHUB_ENV
+            cp composer.json composer.json.orig
+            echo -e '{\n"require":{'"$(grep phpunit-bridge composer.json)"'"php":"*"},"minimum-stability":"dev"}' > composer.json
+            php .github/build-packages.php HEAD^ $SYMFONY_VERSION $(find src/Symfony -mindepth 2 -type f -name composer.json -printf '%h\n' | grep -v src/Symfony/Component/Emoji/Resources/bin)
+            mv composer.json composer.json.phpunit
+            mv composer.json.orig composer.json
+          fi
+          if [[ $SYMFONY_PHPUNIT_BRIDGE_PR ]]; then
+            git rm -fq -- src/Symfony/Bridge/PhpUnit/composer.json
+            git diff --staged -- src/Symfony/Bridge/PhpUnit/ | git apply -R --index
+          fi
+
+          # For the highest branch, in high-deps mode, the version before it is checked out and tested with the locally patched components
+          if [[ "" = high-deps && $SYMFONY_VERSION = $(echo "$SYMFONY_VERSIONS" | tail -n 1 | sed s/.//) ]]; then
+            echo FLIP='^' >> $GITHUB_ENV
+            SYMFONY_VERSION=$(echo "$SYMFONY_VERSIONS" | grep -FB1 /$SYMFONY_VERSION | head -n 1 | sed s/.//)
+            git fetch --depth=2 origin $SYMFONY_VERSION
+            git checkout -m FETCH_HEAD
+            echo COMPONENTS=$(find src/Symfony -mindepth 2 -type f -name phpunit.xml.dist -printf '%h ') >> $GITHUB_ENV
+          fi
+
+          # Skip the phpunit-bridge on bugfix-branches when not in *-deps mode
+          if [[ ! "" = *-deps && $SYMFONY_VERSION != $SYMFONY_FEATURE_BRANCH ]]; then
+            echo COMPONENTS=$(find src/Symfony -mindepth 2 -type f -name phpunit.xml.dist -not -wholename '*/Bridge/PhpUnit/*' | xargs -I{} dirname {}) >> $GITHUB_ENV
+          else
+            echo COMPONENTS=$(find src/Symfony -mindepth 2 -type f -name phpunit.xml.dist | xargs -I{} dirname {}) >> $GITHUB_ENV
+          fi
+
+          # Legacy tests are skipped when deps=high and when the current branch version has not the same major version number as the next one
+          [[ "" = high-deps && $SYMFONY_VERSION = *.4 ]] && echo LEGACY=,legacy >> $GITHUB_ENV || true
+
           echo SYMFONY_VERSION=$SYMFONY_VERSION >> $GITHUB_ENV
           echo COMPOSER_ROOT_VERSION=$SYMFONY_VERSION.x-dev >> $GITHUB_ENV
-          echo SYMFONY_REQUIRE=">=${SYMFONY_VERSION}" >> $GITHUB_ENV
-          echo COLUMNS=150 >> $GITHUB_ENV
+          echo SYMFONY_REQUIRE=">=$([ '' = low-deps ] && echo 5.4 || echo $SYMFONY_VERSION)" >> $GITHUB_ENV
+          [[ "" = *-deps ]] && mv composer.json.phpunit composer.json || true
+
+          if [[ "" = low-deps ]]; then
+            echo SYMFONY_PHPUNIT_REQUIRE="nikic/php-parser:^4.18" >> $GITHUB_ENV
+          fi
+
           composer update --no-progress --ansi
           ./phpunit install
       - name: Install dependencies
@@ -67,12 +145,14 @@ jobs:
             local ok=0
             local title="$1$FLIP"
             OUTPUT=$(bash -xc "$2" 2>&1) || ok=$?
+            echo "::group::"
             if [[ $ok -ne 0 ]]; then
-              printf "::group::%-80s\e[31m%10s\e[0m\n" $title 'FAIL'
+              printf "%-80s\e[31m%10s\e[0m\n" $title 'FAIL'
+              echo "$OUTPUT"
             else
-              printf "::group::%-80s\e[32m%10s\e[0m\n" $title 'OK'
+              printf "%-80s\e[32m%10s\e[0m\n" $title 'OK'
             fi
-            echo "$OUTPUT::endgroup::"
+            echo "::endgroup::"
           }
           export -f _run_tests
           COMPONENTS=$(find src/Symfony -mindepth 2 -type f -name phpunit.xml.dist | xargs -I{} dirname {})
